export const LOCATIONS = {
  India: {
    states: [
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chhattisgarh",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttar Pradesh",
      "Uttarakhand",
      "West Bengal",
      "Andaman and Nicobar Islands",
      "Chandigarh",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Delhi",
      "Jammu and Kashmir",
      "Ladakh",
      "Lakshadweep",
      "Puducherry",
    ],
  },
  "United States": {
    states: [
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "Delaware",
      "Florida",
      "Georgia",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming",
    ],
  },
};

// Full list of all global countries and states stored for easy future access
export const ALL_LOCATIONS = {
  Afghanistan: { states: [] },
  Albania: { states: [] },
  Algeria: { states: [] },
  Andorra: { states: [] },
  Angola: { states: [] },
  "Antigua and Barbuda": { states: [] },
  Argentina: { states: [] },
  Armenia: { states: [] },
  Australia: { states: [] },
  Austria: { states: [] },
  Azerbaijan: { states: [] },
  Bahamas: { states: [] },
  Bahrain: { states: [] },
  Bangladesh: { states: [] },
  Barbados: { states: [] },
  Belarus: { states: [] },
  Belgium: { states: [] },
  Belize: { states: [] },
  Benin: { states: [] },
  Bhutan: { states: [] },
  Bolivia: { states: [] },
  "Bosnia and Herzegovina": { states: [] },
  Botswana: { states: [] },
  Brazil: { states: [] },
  Brunei: { states: [] },
  Bulgaria: { states: [] },
  "Burkina Faso": { states: [] },
  Burundi: { states: [] },
  "Cabo Verde": { states: [] },
  Cambodia: { states: [] },
  Cameroon: { states: [] },
  Canada: { states: [] },
  "Central African Republic": { states: [] },
  Chad: { states: [] },
  Chile: { states: [] },
  China: { states: [] },
  Colombia: { states: [] },
  Comoros: { states: [] },
  Congo: { states: [] },
  "Costa Rica": { states: [] },
  "Cote d'Ivoire": { states: [] },
  Croatia: { states: [] },
  Cuba: { states: [] },
  Cyprus: { states: [] },
  Czechia: { states: [] },
  Denmark: { states: [] },
  Djibouti: { states: [] },
  Dominica: { states: [] },
  "Dominican Republic": { states: [] },
  "DR Congo": { states: [] },
  Ecuador: { states: [] },
  Egypt: { states: [] },
  "El Salvador": { states: [] },
  "Equatorial Guinea": { states: [] },
  Eritrea: { states: [] },
  Estonia: { states: [] },
  Eswatini: { states: [] },
  Ethiopia: { states: [] },
  Fiji: { states: [] },
  Finland: { states: [] },
  France: { states: [] },
  Gabon: { states: [] },
  Gambia: { states: [] },
  Georgia: { states: [] },
  Germany: { states: [] },
  Ghana: { states: [] },
  Greece: { states: [] },
  Grenada: { states: [] },
  Guatemala: { states: [] },
  Guinea: { states: [] },
  "Guinea-Bissau": { states: [] },
  Guyana: { states: [] },
  Haiti: { states: [] },
  Honduras: { states: [] },
  "Hong Kong": { states: [] },
  Hungary: { states: [] },
  Iceland: { states: [] },
  India: {
    states: [
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chhattisgarh",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttar Pradesh",
      "Uttarakhand",
      "West Bengal",
      "Andaman and Nicobar Islands",
      "Chandigarh",
      "Dadra and Nagar Haveli and Daman and Diu",
      "Delhi",
      "Jammu and Kashmir",
      "Ladakh",
      "Lakshadweep",
      "Puducherry",
    ],
  },
  Indonesia: { states: [] },
  Iran: { states: [] },
  Iraq: { states: [] },
  Ireland: { states: [] },
  Israel: { states: [] },
  Italy: { states: [] },
  Jamaica: { states: [] },
  Japan: { states: [] },
  Jordan: { states: [] },
  Kazakhstan: { states: [] },
  Kenya: { states: [] },
  Kiribati: { states: [] },
  Kuwait: { states: [] },
  Kyrgyzstan: { states: [] },
  Laos: { states: [] },
  Latvia: { states: [] },
  Lebanon: { states: [] },
  Lesotho: { states: [] },
  Liberia: { states: [] },
  Libya: { states: [] },
  Liechtenstein: { states: [] },
  Lithuania: { states: [] },
  Luxembourg: { states: [] },
  Madagascar: { states: [] },
  Malawi: { states: [] },
  Malaysia: { states: [] },
  Maldives: { states: [] },
  Mali: { states: [] },
  Malta: { states: [] },
  "Marshall Islands": { states: [] },
  Mauritania: { states: [] },
  Mauritius: { states: [] },
  Mexico: { states: [] },
  Micronesia: { states: [] },
  Moldova: { states: [] },
  Monaco: { states: [] },
  Mongolia: { states: [] },
  Montenegro: { states: [] },
  Morocco: { states: [] },
  Mozambique: { states: [] },
  Myanmar: { states: [] },
  Namibia: { states: [] },
  Nauru: { states: [] },
  Nepal: { states: [] },
  Netherlands: { states: [] },
  "New Zealand": { states: [] },
  Nicaragua: { states: [] },
  Niger: { states: [] },
  Nigeria: { states: [] },
  "North Korea": { states: [] },
  "North Macedonia": { states: [] },
  Norway: { states: [] },
  Oman: { states: [] },
  Pakistan: { states: [] },
  Palau: { states: [] },
  Palestine: { states: [] },
  Panama: { states: [] },
  "Papua New Guinea": { states: [] },
  Paraguay: { states: [] },
  Peru: { states: [] },
  Philippines: { states: [] },
  Poland: { states: [] },
  Portugal: { states: [] },
  Qatar: { states: [] },
  Romania: { states: [] },
  Russia: { states: [] },
  Rwanda: { states: [] },
  "Saint Kitts and Nevis": { states: [] },
  "Saint Lucia": { states: [] },
  "Saint Vincent and the Grenadines": { states: [] },
  Samoa: { states: [] },
  "San Marino": { states: [] },
  "Sao Tome and Principe": { states: [] },
  "Saudi Arabia": { states: [] },
  Senegal: { states: [] },
  Serbia: { states: [] },
  Seychelles: { states: [] },
  "Sierra Leone": { states: [] },
  Singapore: { states: [] },
  Slovakia: { states: [] },
  Slovenia: { states: [] },
  "Solomon Islands": { states: [] },
  Somalia: { states: [] },
  "South Africa": { states: [] },
  "South Korea": { states: [] },
  "South Sudan": { states: [] },
  Spain: { states: [] },
  "Sri Lanka": { states: [] },
  Sudan: { states: [] },
  Suriname: { states: [] },
  Sweden: { states: [] },
  Switzerland: { states: [] },
  Syria: { states: [] },
  Taiwan: { states: [] },
  Tajikistan: { states: [] },
  Tanzania: { states: [] },
  Thailand: { states: [] },
  "Timor-Leste": { states: [] },
  Togo: { states: [] },
  Tonga: { states: [] },
  "Trinidad and Tobago": { states: [] },
  Tunisia: { states: [] },
  Turkey: { states: [] },
  Turkmenistan: { states: [] },
  Tuvalu: { states: [] },
  Uganda: { states: [] },
  Ukraine: { states: [] },
  "United Arab Emirates": { states: [] },
  "United Kingdom": { states: [] },
  "United States": {
    states: [
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "Delaware",
      "Florida",
      "Georgia",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming",
    ],
  },
  Uruguay: { states: [] },
  Uzbekistan: { states: [] },
  Vanuatu: { states: [] },
  "Vatican City": { states: [] },
  Venezuela: { states: [] },
  Vietnam: { states: [] },
  Yemen: { states: [] },
  Zambia: { states: [] },
  Zimbabwe: { states: [] },
};
