export const MARKET_INDICES_BY_COUNTRY = {
  Argentina: ["MERVAL"],
  Australia: ["S&P/ASX 200"],
  Austria: ["ATX"],
  Bangladesh: ["CSE All-Share"],
  Belgium: ["BEL 20"],
  Botswana: ["BSE DCI"],
  Brazil: ["Bovespa"],
  Bulgaria: ["SOFIX"],
  Canada: ["S&P/TSX", "TR Canada 50"],
  Chile: ["IPSA"],
  China: ["Shanghai SE Composite", "SZSE Component"],
  Colombia: ["IGBC"],
  Croatia: ["CROBEX"],
  Czechia: ["PX Index"],
  Denmark: ["OMXC20"],
  Egypt: ["EGX 30"],
  Finland: ["OMXH25"],
  France: ["CAC 40"],
  Germany: ["DAX"],
  Ghana: ["GSE"],
  Greece: ["Athex 20"],
  "Hong Kong": ["Hang Seng"],
  Hungary: ["BUX"],
  Iceland: ["OMX Iceland 10"],
  India: ["Nifty 50", "BSE Sensex"],
  Indonesia: ["LQ45"],
  Iran: ["TEPIX"],
  Ireland: ["ISEQ 20"],
  Israel: ["TA 35"],
  Italy: ["FTSE MIB"],
  Japan: ["Nikkei 225"],
  Jordan: ["ASE"],
  Kazakhstan: ["KASE"],
  Luxembourg: ["LuxX Index"],
  Malaysia: ["FBM KLCI"],
  Mexico: ["IPC Mexbol"],
  Morocco: ["MASI"],
  Netherlands: ["AEX"],
  "New Zealand": ["NZX 50"],
  Norway: ["OBX Index"],
  Oman: ["MSM 30"],
  Pakistan: ["Karachi 100"],
  Philippines: ["PSEi Composite"],
  Poland: ["WIG"],
  Portugal: ["PSI 20"],
  Qatar: ["DSM 200"],
  Romania: ["BET 10"],
  Russia: ["MOEX"],
  "Saudi Arabia": ["Tadawul"],
  Serbia: ["BELEX15"],
  Singapore: ["STI"],
  "South Africa": ["JSE"],
  "South Korea": ["KOSPI"],
  Spain: ["IBEX 35", "IGBM"],
  Sweden: ["OMXS30"],
  Switzerland: ["SMI"],
  Taiwan: ["TAIEX"],
  Thailand: ["SET"],
  Turkey: ["BIST 100"],
  "United Kingdom": ["FTSE 100"],
  "United States": ["Dow Jones Industrial Average", "S&P 500", "Nasdaq"],
  Vietnam: ["HNX 30"],
  Zambia: ["LASI"],
  Europe: ["Euro Stoxx 50", "EURO STOXX 50", "STOXX 600"],
  Global: [
    "MSCI Index",
    "S&P Global 100",
    "S&P Global 1200",
    "The Global Dow",
    "Dow Jones Global Titans 50",
    "FTSE All-World index series",
  ],
};

export const MARKET_INDICES = [
  ...new Set(Object.values(MARKET_INDICES_BY_COUNTRY).flat()),
];

export const getMarketIndicesForCountry = (country) =>
  MARKET_INDICES_BY_COUNTRY[country] || [];
