export const MARKETS = [
  "NYSE",
  "NASDAQ-100",
  "LSE",
  "Japan Exchange Group",
  "Shanghai Stock Exchange",
  "Hong Kong Stock Exchange",
  "Euronext",
  "SZSE Composite Index",
  "Toronto Stock Exchange",
  "Deutsche Börse",
  "BSE",
  "NSE",
  "Six Swiss Exchange",
  "Australian Securities Exchange",
  "OMX Nordic Exchange",
  "JSE Limited",
  "BME Spanish Exchanges",
  "Taiwan Stock Exchange",
  "BM&F Bovespa",
];